name: Deploy Infrastructure

on:
  push:
    branches:
      - main  # Asegúrate que tu rama se llame 'main'. Si es 'master', cambia esto a 'master'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar tu código
    - name: Checkout
      uses: actions/checkout@v3

    # 2. Instalar Terraform en el servidor de GitHub
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # 3. Inicializar (Aquí usa tus claves para descargar plugins de AWS)
    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: 'us-east-1'

    # 4. Planificar (Ver qué va a crear)
    - name: Terraform Plan
      run: terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: 'us-east-1'

    # 5. Aplicar (Crear la infraestructura real)
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: 'us-east-1'
